server:
  port: 9998
  
eureka:
  client:
    service-url:
      default : http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
      
      
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/og88/MicroServerConfig.git